# READ THE CONFIG DOCUMENTATION AT:
# https://github.com/paritytech/parity-bridge/#configuration

# ACTION REQUIRED: set to your authority address
address = "0x41a06892815a450c8bB7297C65290a0864871677"

estimated_gas_cost_of_withdraw = "200000"

# limits total balance on `main` and therefore total ether that could get lost
# if the bridge is faulty or compromised in any way!
# set to `"0"` to disable limit (not recommended at this point)
# currently set to 10 ether.
max_total_main_contract_balance = "10000000000000000000"

# limit `msg.value` for a single deposit into the main contract.
# set to `"0"` to disable limit (not recommended at this point)
# currently set to 1 ether.
max_single_deposit_value = "1000000000000000000"

[main]
# # ACTION REQUIRED: set the the url of the parity node that has `main.account` unlocked
http = "http://13.232.66.43:22000"
# # ACTION REQUIRED: for test deployment set this to 12
required_confirmations = 0

[main.contract]
# # READ THE CONFIG DOCUMENTATION AT:
# # https://github.com/paritytech/parity-bridge/#configuration
bin = "../parity-bridge/compiled_contracts/Main.bin"

[side]
# ACTION REQUIRED: set the the url of the parity node that has `side.account` unlocked
http = "http://localhost:8540"
# ACTION REQUIRED: for test deployment set this to 12
required_confirmations = 0

[side.contract]
# READ THE CONFIG DOCUMENTATION AT:
# https://github.com/paritytech/parity-bridge/#configuration
bin = "../parity-bridge/compiled_contracts/Side.bin"

[authorities]
# ACTION REQUIRED: set this to the addresses of the authority list
accounts = [
	"0x41a06892815a450c8bB7297C65290a0864871677",
]
# ACTION REQUIRED: set this to a (super-)majority of `authorities.accounts`
# example: set to 3 for 5 authorities. set to 7 for 10 authorities
required_signatures = 1

[transactions]
# `gas` below should be good defaults for test deployment.
# ACTION REQUIRED: you have to set `gas_price` for each transaction
# if your authority can't do free transactions on the chain.
# `gas_price` might need adjustment once in a while.

# these happen on `main`:
main_deploy = { gas = "1500000" , gas_price = "25" }
withdraw_relay = { gas = "200000" , gas_price = "25" }

side_deploy = { gas = "3000000" , gas_price = "25" }
deposit_relay = { gas = "150000" , gas_price = "25" }

withdraw_confirm = { gas = "300000" , gas_price = "0" }